# Site wide configuration

title:            Jeung-Hyun Lee
locale:           en_US
url:              https://jeunghyunlee.github.io/ # used in page head for the canonical header, RSS link and feed.xml
# baseurl:          "/"   # indicates the root folder of your Jekyll site => used for internal links 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-scholar

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
plugins:
  - jekyll-feed
  - jekyll-liquid-debugger

# Site owner
owner:
  name: Jeung-Hyun Lee
  avatar: avatar.jpg
  bio: "Stress & Computational psychiatry, Decision-making neuroscience"
  location: "Seoul, Korea"
  email: jeunghyunleee@mail.com
  disqus-shortname: Jeung-Hyun Lee
  twitter: JeunghyunLee
  googlescholar: citations?user=-mHgxD8AAAAJ&hl=ko
  facebook: #username
  google:
  #  plus: MartinGrossMG
  analytics: G-ZB65XDX2W6
  #  verify: 7TRemu2QpSnAN1yRsZdRVF7hjAdPU6lMxGzRvfoESRI
  #  ad-client:
  #  ad-slot: 
  bing-verify: 
  github: JeunghyunLee
  # stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: Jeung-hyun-lee-812216164
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]


